### PR TITLE
Pin flake version in dev dependencies

### PR DESCRIPTION
**Pull request by GregaVrbancic**
Trying to address the issue in PR #390

### CODE REVIEW

**Comment by GregaVrbancic** [comment]
I am having issues with reproducing the error on my machine. Can maybe @firefly-cpp or @zStupan test pinning the flake and pycodestyle dependency versions?

**Comment by zStupan** [comment]
@GregaVrbancic I'm struggling to even get pipenv working on Ubuntu 22.04, It throws errors when trying to run pip install. I get the error `AttributeError: module 'collections' has no attribute 'MutableMapping'`, which is related to setuptools (https://stackoverflow.com/questions/69512672/getting-attributeerror-module-collections-has-no-attribute-mutablemapping-w). But updating still doesn't fix it. I think it's about time we switch to poetry.

**Comment by zStupan** [comment]
Problems with flake are fixed by #395. This PR can be closed.
